# Generated by Django 4.1 on 2023-09-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Topic',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='category',
        ),
        migrations.AddField(
            model_name='insight',
            name='topic',
            field=models.ManyToManyField(to='core.topic', verbose_name='topics'),
        ),
        migrations.AddField(
            model_name='insight',
            name='section',
            field=models.ManyToManyField(to='core.section', verbose_name='sections'),
        ),
    ]
