# Generated by Django 4.1 on 2023-09-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section_rename_category_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='header_image',
            field=models.FileField(null=True, upload_to='insight/'),
        ),
    ]
